---
- name: "(SUSE/SLES) Chain Certificates"
  shell: cat /etc/ssl/nginx/nginx-repo.crt /etc/ssl/nginx/nginx-repo.key > /etc/ssl/nginx/nginx-repo-bundle.crt

- name: "(SUSE/SLES) Add NGINX Plus Repository"
  zypper_repository:
    name: nginx-plus
    repo: https://plus-pkgs.nginx.com/sles/12?ssl_clientcert=/etc/ssl/nginx/nginx-repo-bundle.crt&ssl_verify=host
    disable_gpg_check: yes
