---
- name: "(CentOS/RedHat) Add NGINX Plus Repository"
  get_url:
    url: https://cs.nginx.com/static/files/nginx-plus-{{ansible_distribution_major_version|int}}.repo
    dest: /etc/yum.repos.d/nginx-plus-{{ansible_distribution_major_version|int}}.repo
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: "(AWS Linux) Add NGINX Plus Repository"
  get_url:
    url: https://cs.nginx.com/static/files/nginx-plus-{{ansible_distribution|lower}}.repo
    dest: /etc/yum.repos.d/nginx-plus-{{ansible_distribution|lower}}.repo
  when: ansible_distribution == "Amazon"
