---
- name: "(CentOS/RedHat) Add NGINX Plus Repository"
  get_url:
    url: https://cs.nginx.com/static/files/nginx-plus-{{ansible_distribution_major_version|int}}.repo
    dest: /etc/yum.repos.d/nginx-plus-{{ansible_distribution_major_version|int}}.repo
